// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";
import type { TokenType } from "./TokenType";

/**
 * A span annotation on the formal proof source.
 *
 * Either a semantic token (for syntax highlighting) or a diagnostic
 * (for error/warning squiggles). All line numbers are 1-indexed.
 */
export type Annotation =
  | {
      kind: "token";
      line: number;
      col: number;
      length: number;
      tokenType: TokenType;
      modifiers: Array<string>;
    }
  | {
      kind: "diagnostic";
      startLine: number;
      startCol: number;
      endLine: number;
      endCol: number;
      severity: DiagnosticSeverity;
      message: string;
    };
