// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisconnectReason } from "./DisconnectReason";

/**
 * Connection status of the Proof Assistant (the LLM backend).
 *
 * Mirrors the [`LspStatus`] pattern: recorded in `AppState` and emitted to the
 * frontend as a [`TurnstileMessage::AssistantStatus`] on startup and on change,
 * recoverable via the `get_assistant_status` command. The `Disconnected`
 * `reason` never contains the API key.
 */
export type AssistantStatus = { "state": "connected" } | { "state": "disconnected", reason: DisconnectReason, };
