// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GutterMark } from "./GutterMark";
import type { HoverHit } from "./HoverHit";
import type { SyntaxColor } from "./SyntaxColor";
import type { Underline } from "./Underline";

/**
 * The complete set of `CodeMirror`-ready annotation views.
 *
 * Derived from an [`LSPAnnotation`] against a specific source. This is the
 * payload the frontend renders; it carries no line/col, only resolved offsets.
 */
export type DerivedAnnotations = { syntaxColoring: Array<SyntaxColor>, underlines: Array<Underline>, gutter: Array<GutterMark>, hover: Array<HoverHit>, };
