// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticInfo = { start_line: number, start_col: number, end_line: number, end_col: number, severity: number, message: string, };
