// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Diagnostic severity level.
 */
export type DiagnosticSeverity = "error" | "warning" | "info" | "hint";
