// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the Proof Assistant is disconnected. Drives the distinct toast messages
 * in the failure-surfacing story (#60). Never carries the API key.
 */
export type DisconnectReason = "noKey" | "keyRejected" | "storeUnavailable";
