// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range of lines currently being elaborated by the Lean server.
 * Emitted via the `$/lean/fileProgress` notification.
 */
export type FileProgressRange = { start_line: number, end_line: number, };
