// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalCacheRow } from "./GoalCacheRow";

/**
 * A full snapshot of the per-row goal cache, delivered to the UI via
 * [`crate::lean::messages::turnstile::TurnstileMessage::GoalCacheUpdated`].
 * Display is a pure function of `(cursor row, this snapshot)`.
 */
export type GoalCacheInfo = { 
/**
 * Cached rows, ascending. `Stale`/`Empty` rows are included so the
 * frontend can drop a card the instant its row goes stale.
 */
rows: Array<GoalCacheRow>, };
