// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Goal state returned by Lean at the end of the document.
 */
export type GoalStateInfo = { full: string };
