// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open goal in structured form (ADR-0004 decision 6).
 *
 * An optional `case` label, its hypotheses, and the `⊢` conclusion. Parsed
 * once in the backend from a `$/lean/plainGoal` `goals[]` entry, so the
 * frontend renders structure rather than re-splitting text.
 */
export type GoalEntry = { caseLabel: string | null, hypotheses: Array<string>, conclusion: string, };
