// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalEntry } from "./GoalEntry";
import type { GoalRowStatus } from "./GoalRowStatus";

/**
 * One row in a [`GoalCacheInfo`] snapshot: a 1-indexed line number with its
 * cached status and goals. Flattened from the cache for the wire.
 */
export type GoalCacheRow = { 
/**
 * 1-indexed line number (matching the `CodeMirror` / frontend convention).
 */
row: number, status: GoalRowStatus, goals: Array<GoalEntry>, };
