// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a row's cached goal (ADR-0004). Display renders a card for a row
 * **iff** its status is `Fresh`.
 */
export type GoalRowStatus = "fresh" | "stale" | "empty";
