// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

/**
 * One gutter mark, addressing a whole (1-indexed) line.
 */
export type GutterMark = { line: number, severity: DiagnosticSeverity, };
