// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

/**
 * One diagnostic hover target: a `[from, to]` UTF-16 offset span and the
 * message to show when the cursor falls within it.
 */
export type HoverHit = { from: number, to: number, severity: DiagnosticSeverity, message: string, };
