// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SemanticToken = {
  line: number;
  col: number;
  length: number;
  token_type: string;
  token_modifiers: Array<string>;
};
