// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenType } from "./TokenType";

/**
 * One syntax-colouring span: a half-open `[from, to)` UTF-16 offset range and
 * the token type that selects its CSS class.
 */
export type SyntaxColor = { from: number, to: number, tokenType: TokenType, };
