// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { DiagnosticInfo } from "./DiagnosticInfo";
import type { FileProgressRange } from "./FileProgressRange";
import type { GoalStateInfo } from "./GoalStateInfo";
import type { LspStatus } from "./LspStatus";
import type { SemanticToken } from "./SemanticToken";

/**
 * Wire format from the Rust backend to the JS frontend for the Lean / LSP
 * layer. All in-scope `app.emit` calls go through `emit_turnstile`, which
 * logs the message at `debug` level and emits it under the
 * `"turnstile-message"` event name.
 *
 * Other subsystems (LLM, session, setup, prose, menu) currently emit their
 * own events directly and are not represented here.
 */
export type TurnstileMessage =
  | ({ type: "diagnostics" } & Array<DiagnosticInfo>)
  | ({ type: "annotationsUpdated" } & Array<Annotation>)
  | ({ type: "fileProgress" } & Array<FileProgressRange>)
  | { type: "elaborationDone" }
  | { type: "showMessage"; severity: string; message: string }
  | ({ type: "lspStatus" } & LspStatus)
  | { type: "semanticTokenRefresh" }
  | ({ type: "semanticTokens" } & Array<SemanticToken>)
  | ({ type: "goalStateUpdated" } & GoalStateInfo);
