// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

/**
 * One diagnostic underline: a half-open `[from, to)` UTF-16 offset range and
 * the severity that selects its CSS class.
 */
export type Underline = { from: number, to: number, severity: DiagnosticSeverity, };
